### ISSUE TITLE
Mode to print single bytes as ASCII if possible

### ISSUE THREAD

**Issue by pothos** [8051Enthusiast/biodiff#1]
Thanks for publishing your work. What do you think about having a mode (not default but available in F4) to print those bytes which have a printable ASCII character assigned as ASCII instead of the hex number?
E.g.,
```
ff \n  a
```
instead of
```
ff 0a 61
```
where the leading space for ` a` makes it clear that it is ASCII and not hex, and common escaped characters could also be shown as \n, \r, or \t etc.

**Comment by 8051Enthusiast** [comment]
Oh yes I would definitely like to introduce more display modes. Do you have any idea what to use for space?
* literal space could be confused with gaps
* `20` would theoretically work, but isn't intuitively recognizable as space
* `␣` could work, but I'm not sure how wide the unicode support for that is
* `·` (interpunct) is confusable with dots
* `␠` (symbol for space) is hard to read and not very space-y
* `__` (two underscores) maybe? it could still be distinguishied from a single one

**Comment by pothos** [comment]
Hm, maybe a leading backslash?
```
fe \   a
```
I like the idea of using unicode but a special combination would also work when explained in the help.
(And by the way, very nice TUI, will have to read your code)

**Comment by 8051Enthusiast** [comment]
I somehow missed the obvious choice huh. In any case, it can always be changed later so it's not that important for now.

The dialogs are actually from [cursive](https://github.com/Gyscos/Cursive).
The hex viewer is actually using a lower-level library, but when opening a library, it switches to cursive in a somewhat hacky way.

(I did it this way because initially cursive was very flickery, however that was fixed with [cursive_buffered_backend](https://github.com/agavrilov/cursive_buffered_backend). I'm still keeping the hack though because a refresh redraws the whole screen even if just the cursor moves and I can do more selective refreshes, which is probably a nicer experience for slower terminals)

**Comment by 8051Enthusiast** [comment]
The current dev branch includes this mode, along with a bunch of other stuff. I will probably release a new version soon that contains it.

It now uses two dots `..` for space, and the printable ASCII characters are displayed as full-width unicode characters (and in different colors) because it makes string way more readable.

**Comment by pothos** [comment]
Nice, I tried it out and it works well :)

Since you used full-width unicode characters already, I tried out to use the full-with dashed low line `﹍` (U+FE4D) for the space character and it is a bit easier for the eyes to read. What do you think?

**Comment by 8051Enthusiast** [comment]
Thanks for the suggestion, it does look better so i changed it. Will probably do a release tomorrow which includes this feature.

**Comment by pothos** [comment]
Thanks, feel free to close this issue. One more suggestion for the ASCII column: There the space can be a regular space which is also done by `hexdump -C`. Since the bytes are shown in the other column it shouldn't be too confusing where the start and end is.

**Comment by 8051Enthusiast** [comment]
Hmm, i thought i already did that but apparently not. Oh well, now it does. Thank you, I'm closing this then.
