### ISSUE TITLE
Non-TUI mode to allow piping output etc

### ISSUE THREAD

**Issue by wader** [8051Enthusiast/biodiff#12]
Hi, would it be possible to add a non-TUI mode to allow piping to less etc? if so i guess some command line arguments would be convenient also.

**Comment by 8051Enthusiast** [comment]
Sure, I already have different terminal backends, it shouldn't be hard for me to add a plaintext one.

This does of course require arguments, but i'm not quite sure how many arguments i would like to expose yet - i'm planning to add other alignment algorithms (for example biwfa from wfa2-lib) and i feel like that would quickly become unwieldy.

**Comment by wader** [comment]
Ok nice and no stress! i think it would be a nice feature

**Comment by 8051Enthusiast** [comment]
Hi, it's been some time (had a mild compiler addiction) but current `main` now has proper arguments and you can print the output to stdout using `biodiff --print file1 file2`.
To make algorithm choice easier, I've also added a preset system so you could add `-gglobal` to use the global preset which aligns the whole file instead of blockwise.

**Comment by wader** [comment]
Great thanks! will try it out
