### ISSUE TITLE
Feature request: Jump to previous difference

### ISSUE THREAD

**Issue by MatejKafka** [8051Enthusiast/biodiff#14]
Currently, it is possible to jump to the next difference by pressing `space`. I'd like to jump to the previous difference by pressing `shift+space` (or any other convenient shortcut).

**Comment by 8051Enthusiast** [comment]
This is actually already implemented: you can jump to the previous difference with shift+up arrow (or shift+k if that doesn't work). You can also jump to the previous/next insertion with ctrl+up/down (or ctrl+k/j). I've decided not to extend space with modifiers since that does not work well with some terminals...

**Comment by MatejKafka** [comment]
Oh, apologies, missed that. Thanks. :)
